

name: Release mod to Github, Curseforge and Modrinth

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.2
  JAVA_VERSION: 17
  VERSION: 1.0.1
  RELEASE_NAME: ResourcePack Server ${{ env.VERSION }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: env

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: make Gradle Wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew clean build

      - name: release（CurseForge/Modrinth/Github）
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 922731
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: GPtCh1IV
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

